server:
  port: 8083

spring:
  application:
    name: job-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/jobapp_jobs}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

cache:
  redis:
    time-to-live: 600000 # 10 minutes

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
  health:
    mongo:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    com.jobapp.job: DEBUG
    org.springframework.boot.actuator: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: logs/job-service.log
    max-size: 10MB
    max-history: 30

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true
  group-configs:
    - group: 'jobs'
      display-name: 'Job Management API'
      paths-to-match: '/api/jobs/**'
    - group: 'search'
      display-name: 'Job Search API'
      paths-to-match: '/api/search/**'
    - group: 'actuator'
      display-name: 'Actuator Endpoints'
      paths-to-match: '/actuator/**'